version: "3.8"

services:
    mysql:
        image: mysql:5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: notary-db
        ports:
            - "3306:3306"
