# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
    pull_request:
        paths-ignore: ['.editorconfig', '.vscode/', '.gitignore', '.huskyrc.json', '.lintstagedrc.json', 'commitlint.config.js', '.prettierrc', 'CODE_OF_CONDUCT', '.github/ISSUE_TEMPLATE/**', '.github/PULL_REQUEST_TEMPLATE.md', 'README.md', 'docs/**']
        branches: [master, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install Dependencies
              run: npm install
            - name: Build Project
              run: npm run build
            # - name: Test Project
            #   run: npm run test:cov
            # - name: Upload Coverage to Codecov
              # uses: codecov/codecov-action@v1
              # with:
                # token: ${{ secrets.CODECOV_TOKEN }}
            - name: Lint Project
              run: npm run lint
