name: Deploy Staging

on:
    push:
        paths-ignore: ['.editorconfig', '.gitignore', '.prettierrc', 'CODE_OF_CONDUCT', '.github/ISSUE_TEMPLATE/**', '.github/PULL_REQUEST_TEMPLATE.md', 'README.md', 'docs/**']
        branches: [dev]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "notary101-dev"
                heroku_email: ${{secrets.HEROKU_ACCOUNT_EMAIL}}
                usedocker: true
                stack: "container"
